### PR TITLE
Augment and enrich demodata

### PR DESCRIPTION
**Pull request by lmperry**
Once the data have been uploaded to an instance, use  https://github.com/scitran/utilities/blob/master/demodata_configure_db.py to update the DB, and make things even more fun. 

Note that the QA fMRI gear need not run on these demodata, as demo qa_reports have been added to each fMRI data acquisition.

### CODE REVIEW

**Comment by gsfr** [comment]
How the hell do you expect anyone to review this? You changed over 3000 files! Github can't even show the diff. 😉

Thanks, @lmperry. @ryansanford and I will test this out tomorrow and get back to you.

**Comment by lmperry** [comment]
Fair enough... I just added 5 more :)

**Comment by ryansanford** [comment]
@lmperry Is there a script for creating the symlinks in an approved way for HBM demo?

**Comment by lmperry** [comment]
@ryansanford: not at the moment. I considered writing something to convert a single group, project, subject, session, acquisition into any arbitrary number of each, however it quickly grew in complexity and scope while the benefit over getting something up here now, which works and can be manually pruned, was not clear. 

Did anyone try to upload it and use the script to fiddle with the DB?

**Comment by ryansanford** [comment]
@lmperry my laptop crashed overnight while loading the data. I believe that was unrelated to the data, and had more to do with docker mac beta. I'm loading again now in a prod environment.

**Comment by ryansanford** [comment]
@lmperry All data loaded into a single core system in about 40 minutes. dcm-convert and dicom-mr-classifier gears are still processing the data after 4 hours. I think my plan for staging the demo VM will be to restore the data and DB partitions onto the VM. I've done that successfully before to replicate demo and beta systems.

What specifically am I looking for to confirm https://github.com/scitran/utilities/blob/master/demodata_configure_db.py changed what it was supposed to?

**Comment by lmperry** [comment]
@ryansanford Sounds good. 

Ideally the script should be run once the gears finish (no need to run the QA gear, as above). To verify that the script worked, you should have named groups (Clinical Group, Psychology Group, and Neuroscience Group), and each session should have a subject tab that looks like this: 

screen shot 2016-06-21 at 1 07 09 pm

**Pull request merged**
